# Generated by Django 5.0 on 2023-12-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
