# Generated by Django 5.0 on 2023-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(null=True, upload_to='news_video'),
        ),
    ]
