# Generated by Django 5.0 on 2023-12-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_news_category_alter_news_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'IP manzil',
                'verbose_name_plural': 'IP manzillar',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.ManyToManyField(blank=True, related_name='news_views', to='home.ipmodel'),
        ),
    ]
