# Generated by Django 5.0 on 2023-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ipmodel_remove_news_view_count_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='IPModel',
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
